### ISSUE TITLE
Clarify documentation so highlightjs doesn't run again

### ISSUE THREAD

**Issue by omundy** [bylexus/grunt-md2html#24]
If you add highlightjs in the gruntfile AND link to it from the template with a full url to the CDN the script will run twice and generate these warnings. Per this [issue](https://github.com/highlightjs/highlight.js/issues/2886) the fix is to only run highlight once. The [documentation](https://github.com/bylexus/grunt-md2html#optionshighlightjs) could be improved to either organize the `options.highlightjs` sample at the beginning under method 2 to add it. Or, just add text to the end of method 1 that says "If you use this method then don't add highlightjs to your options in the gruntfile or it will run twice."

![Screen Shot 2021-12-27 at 8 04 10 AM](https://user-images.githubusercontent.com/279945/147474717-43145800-1655-4880-b4f6-509c976ff4b4.png)

**Comment by omundy** [comment]
After more research I need to update this. If I use the following code (with the `json` language tag) and use only highlightjs in the template then I still receive the above warnings.
```
```json
{
  "status": "OK"
}
```


md2html generates this html:
![Screen Shot 2021-12-27 at 8 46 07 AM](https://user-images.githubusercontent.com/279945/147477789-46fa6169-3c4e-4e07-8945-8476cbf5eec7.png)

But if I remove the `json` language tag from the opening backticks in the markdown the order of the `hljs language-json` classes are swapped and it does not generate an error: 
![Screen Shot 2021-12-27 at 8 46 44 AM](https://user-images.githubusercontent.com/279945/147477792-94b833a3-c090-402b-8345-0049e36fdecd.png)

I'm not sure that the re-ordering of the classes isn't just a symptom of the problem. I can say that if I remove highlightjs from the template the `language-json` still appears, so clearly md2html is altering the code. So this actually may be a 2nd issue?

**Comment by bylexus** [comment]
I will have a look into that matter. The today's solution is clearly not what I originally intended :-)

**Comment by omundy** [comment]
Well I'm thankful because the project is working great for me. 
1. LMK if I can submit the correction to the documentation as a PR.
2. I can't find anything in the codebase to change how the project adds the class to `code` blocks. I can submit a 2nd issue about that if you prefer?

**Comment by bylexus** [comment]
to 1) Yes, please do so. For the time being, this would just be a workaround (updating the doc), I want to fix it, but need some time.
to 2) This is done by highlightjs itself: it manipulates the DOM, and it may be that the double-runs here causes some trouble... Again, I need to investigate in that, but I'm fine with that one issue.

**Comment by bylexus** [comment]
Closed by PR #25
