### ISSUE TITLE
One .md to one .html files does not work

### ISSUE THREAD

**Issue by jfox015** [bylexus/grunt-md2html#5]
Nice Grunt Task first off. 

Secondly, I'm trying to use to the task to generate a single .html file for each .md input file but no matter how I arrange the options, the task only compiles all the .md source files into a single .html file. Looking at the source code for the task, I only see one operation in the foreach loop that parses the marked data against the templates and then joins the output. Is the 1 => 1 conversion not available or have I missed something config wise? Here's my grunt task config:

    md2html: {
            multiple_files: {
              options: {
                layout: '_assets/templates/markdown.tpl'
              },
              files: [{
                expand: true,
                cwd: './_markdown/',
                src: ['*.md'],
                dest: './_markdown/_compiled/',
                ext: '.html'
              }]
            }
          },

**Comment by bylexus** [comment]
Dear Jeff,

Thanks for the input. I just tried with your config, and I cannot reproduce the error. I paste my complete Gruntfile.js, perhaps this helps you:

```javascript
module.exports = function(grunt) {
    grunt.initConfig({
        md2html: {
            multiple_files: {
                options: {
                    layout: '_assets/templates/markdown.tpl'
                },
                files: [{
                    expand: true,
                    cwd: './_markdown/',
                    src: ['*.md'],
                    dest: './_markdown/_compiled/',
                    ext: '.html'
                }]
            }
        },
    });

    grunt.loadNpmTasks('grunt-md2html');
};
```

Build with: `grunt md2html`. Maybe you have some more details / inputs?

**Comment by jfox015** [comment]
@bylexus I'll post some more of my setup. I did notice by tracing the function in md2html.js that the output file name is automatically set to "html.html" before the processing loop even starts. Is this right? Shouldn't the foreach loop read each file name and create a matching .html?

**Comment by bylexus** [comment]
Jeff,

I am really sorry, but I cannot see the point: The `this.files` array is already expanded by Grunt's `grunt.file.expandMapping` function: This function already creates the correct output destination file name.

I just console.logged the `f` variable as a first statement in the forEach loop to test what's going on, with the same config as above, and with the following result:

```
grunt md2html
Running "md2html:multiple_files" (md2html) task
Using layout file: _assets/templates/markdown.tpl
{ src: [ '_markdown/file1.md' ],
  dest: '_markdown/_compiled/file1.html',
  orig:
   { expand: true,
     cwd: './_markdown/',
     src: [ '*.md' ],
     dest: './_markdown/_compiled/',
     ext: '.html' } }
File "_markdown/_compiled/file1.html" created.
{ src: [ '_markdown/file2.md' ],
  dest: '_markdown/_compiled/file2.html',
  orig:
   { expand: true,
     cwd: './_markdown/',
     src: [ '*.md' ],
     dest: './_markdown/_compiled/',
     ext: '.html' } }
File "_markdown/_compiled/file2.html" created.
```

As you can see here, the output files are correctly named.

If it helps, I have placed you the above complete example for downloading on my google drive box:

https://drive.google.com/file/d/0B3qkcD75xynPck1mWHdOZ0dRVnc/view?usp=sharing

Hope with this example you can find the problem.

**Comment by jfox015** [comment]
@bylexus Thanks for sending the example zip! The big difference I see between my stuff and your example is the .tpl file is a complete HTML document where as mine is just a chuck of an HTML page. I did get some warnings from marked compiling the first few times so I'm wondering of that might be a factor. 

My tpl file

     <div class="col">
          <%= document %> 
     </div>

My goal is to take a set of small MD content snippets, compile them into HTML versions using a snippet template, then use the Assemble Grunt Task (or my own custom task using Handlebars or other template tool) to combine them into a single html doc that will resemble the final output of [codeguide](http://codeguide.co/).

**Comment by bylexus** [comment]
Jeff,
Even then, this behavior makes no sense: The content of the layout file is not relevant for the process. I can really not reproduce the problem you encounter.

Do you have the possibility to post a working (or, should I say, 'non-working' ;-) ) example like the one I sent? I will try to find out what's going on then. This seems to be a strange behaviour which I am not able to replay.
Thanks

**Comment by jfox015** [comment]
@bylexus OK, I zipped what I'm working on, Here's the Google Drive link:

https://drive.google.com/file/d/0B500yJsQQtWdZkh6S0NiNmtiS0U/view?usp=sharing

**Comment by bylexus** [comment]
Ah, now I see a bit clearer:
Your original .md-files are named `html.syntax.md` and `html.doctype.md`. Grunt's `grunt.file.expandMappiing` function removes / replaces file endings "greedily" by default, meaning it replaces the string from the first occurence of a dot. (like in `file.tar.gz`).

Luckily there is a solution: Just set the `extDot` file property to `last` in the Gruntfile:

```
md2html: {
            multiple_files: {
              options: {
                layout: '_assets/templates/markdown.tpl'
              },
              files: [{
                expand: true,
                cwd: './_markdown/',
                src: ['*.md'],
                dest: './_markdown/_compiled/',
                ext: '.html',
                extDot: 'last'
              }]
            }
        },
```
and from now on, it names the files as expected.

See http://gruntjs.com/api/grunt.file#grunt.file.expandmapping

Hope that helps,
alex

**Comment by jfox015** [comment]
@bylexus Hoorah! That did it. Thank you for your help and patience through my obvious lack of Grunts file handling capabilities. Cheers!

**Comment by bylexus** [comment]
Glad I could help. It's always a pleasure to see that my tools are useful for others.
